const TILE_OUT_OF_BOUNDS = -1;
const TILE_EMPTY = 0;
const TILE_BROWN_GROUND = 1;
const TILE_BLUE_SKY = 2;

const TILE_CLOUD_UL = 3;
const TILE_CLOUD_UC = 4;
const TILE_CLOUD_UR = 5;
const TILE_CLOUD_LL = 6;
const TILE_CLOUD_LC = 7;
const TILE_CLOUD_LR = 8;

const TILE_BUSH_LEFT = 9;
const TILE_BUSH_CENTER = 10;
const TILE_BUSH_RIGHT = 11;

const TILE_HILL_LEFT = 12;
const TILE_HILL_TOP = 13;
const TILE_HILL_RIGHT = 14;
const TILE_HILL_EYES = 15;
const TILE_HILL_NOEYES = 16;
