const TILE_OUT_OF_BOUNDS = -1;
const TILE_EMPTY = 0x00;
const TILE_BLUE_SKY = 0x02;

const TILE_BLUE_ROCKS = 0x1f;
const TILE_BLUE_BLOCK = 0x20;
const TILE_BLUE_BRICK_BLOCK = 0x21;
const TILE_UNDERGROUND_PIPE_TOP_END_LEFT = 0x22;
const TILE_UNDERGROUND_PIPE_TOP_END_RIGHT = 0x23;
const TILE_UNDERGROUND_PIPE_V_LEFT = 0x24;
const TILE_UNDERGROUND_PIPE_V_RIGHT = 0x25;
const TILE_UNDERGROUND_PIPE_H_TOP = 0x26;
const TILE_UNDERGROUND_PIPE_H_BOTTOM = 0x27;
const TILE_UNDERGROUND_PIPE_LEFT_END_TOP = 0x28;
const TILE_UNDERGROUND_PIPE_LEFT_END_BOTTOM = 0x29;
const TILE_UNDERGROUND_PIPE_LEFT_INT_TOP = 0x2a;
const TILE_UNDERGROUND_PIPE_LEFT_INT_BOTTOM = 0x2b;
