const TILE_OUT_OF_BOUNDS = -1;
const TILE_EMPTY = 0;
const TILE_BLUE_SKY = 2;

const TILE_CLOUD_UL = 3;
const TILE_CLOUD_UC = 4;
const TILE_CLOUD_UR = 5;
const TILE_CLOUD_LL = 6;
const TILE_CLOUD_LC = 7;
const TILE_CLOUD_LR = 8;

const TILE_HILL_LEFT = 12;
const TILE_HILL_TOP = 13;
const TILE_HILL_RIGHT = 14;
const TILE_HILL_EYES = 15;
const TILE_HILL_NOEYES = 16;

const TILE_CASTLE_TOP = 17;
const TILE_CASTLE_WINDOWLEFT = 18;
const TILE_CASTLE_WINDOWRIGHT = 19;
const TILE_CASTLE_BRICKS = 20;
const TILE_CASTLE_DOORTOP = 21;
const TILE_CASTLE_DOORMIDDLE = 22;
const TILE_CASTLE_TOPMIDDLE = 23;

const TILE_PIPE_TOP_LEFT = 24;
const TILE_PIPE_TOP_RIGHT = 25;
const TILE_PIPE_MID_LEFT = 26;
const TILE_PIPE_MID_RIGHT = 27;

const TILE_FLAGPOLE_TOP = 28;
const TILE_FLAGPOLE_MID = 29;

const TILE_UNDERGROUND_BG = 30;
const TILE_BLUE_ROCKS = 31;
const TILE_BLUE_BLOCK = 32;
const TILE_BLUE_BRICK_BLOCK = 33;
const TILE_UNDERGROUND_PIPE_TOP_END_LEFT = 34;
const TILE_UNDERGROUND_PIPE_TOP_END_RIGHT = 35;
const TILE_UNDERGROUND_PIPE_V_LEFT = 36;
const TILE_UNDERGROUND_PIPE_V_RIGHT = 37;
const TILE_UNDERGROUND_PIPE_H_TOP = 38;
const TILE_UNDERGROUND_PIPE_H_BOTTOM = 39;
const TILE_UNDERGROUND_PIPE_LEFT_END_TOP = 40;
const TILE_UNDERGROUND_PIPE_LEFT_END_BOTTOM = 41;
const TILE_UNDERGROUND_PIPE_LEFT_INT_TOP = 42;
const TILE_UNDERGROUND_PIPE_LEFT_INT_BOTTOM = 43;

const TILE_SOLID_BLOCK = 44;
const TILE_ITEM_BLOCK = 45;
const TILE_TREE_TOP_LEFT = 46;
const TILE_TREE_TOP_CENTER = 47;
const TILE_TREE_TOP_RIGHT = 48;
const TILE_TREE_TRUNK = 49;

const TILE_CASTLE_LAVA_TOP = 52;
const TILE_CASTLE_LAVA_MIDDLE = 53;
const TILE_CASTLE_BRIDGE = 56;
const TILE_CASTLE_CHAIN = 57;
const TILE_CASTLE_AXE = 58;
